### ISSUE TITLE
Python v3.9 - ModuleNotFoundError: No module named 'requests' after updating system

### ISSUE THREAD

**Issue by jojoax** [grrttedwards/wow-addon-updater#164]
** on Rolling Releas Arch Linux, after running a system update, the import of the "request" module from sit installtion Py v3.9 fails **
What are you seeing when you run the script?

[jojo@pc7 wow-addon-updater]$ ./run_MacLinux.sh 
++ pipenv run python3 -m updater
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/usr/games/wow/_classic_/Interface/script/wow-addon-updater/updater/__init__.py", line 1, in <module>
    import updater.manager
  File "/usr/games/wow/_classic_/Interface/script/wow-addon-updater/updater/manager/__init__.py", line 1, in <module>
    from .addon_manager import AddonManager
  File "/usr/games/wow/_classic_/Interface/script/wow-addon-updater/updater/manager/addon_manager.py", line 13, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
++ read -n1 -r -p 'Press anything to close...'
Press anything to close...

**If you run `pipenv update` on the command line and try again, does the issue go away?**
 No
[jojo@pc7 wow-addon-updater]$ pipenv update
Running $ pipenv lock then $ pipenv sync.
Locking [dev-packages] dependencies...
Building requirements...
Resolving dependencies...
✘ Locking Failed! 
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pipenv/resolver.py", line 763, in <module>
    main()
  File "/usr/lib/python3.9/site-packages/pipenv/resolver.py", line 747, in main
    _patch_path(pipenv_site=parsed.pipenv_site)
  File "/usr/lib/python3.9/site-packages/pipenv/resolver.py", line 42, in _patch_path
    pipenv_dist, pipenv_path = find_site_path("pipenv", site_dir=pipenv_site)
  File "/usr/lib/python3.9/site-packages/pipenv/resolver.py", line 14, in find_site_path
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'

**Log output**
Please include the contents of `addon-updater.log`, from the root of the directory.
Either copy-paste the contents, or attach the file to this issue.
No Log file is to be written sinc the code crashes in total

**Comment by smo0z** [comment]
I deleted $HOME/.local/share/virtualenv and virtualenvs, rerun pipenv install and now it works again.

**Comment by grrttedwards** [comment]
@jojoax Does this fix that @smo0z posted work for you?

> I deleted $HOME/.local/share/virtualenv and virtualenvs, rerun pipenv install and now it works again.

**Comment by kruesephiikz** [comment]
Confirming that removing `$HOME/.local/share/virtualenv and virtualenvs` fixes the issue on ArchLinux

**Comment by jojoax** [comment]
Confirmed. The pipenv environment did not really a working update.
