### ISSUE TITLE
Tukui -- Failed to find addon version number for game version

### ISSUE THREAD

**Issue by RavenDT** [grrttedwards/wow-addon-updater#165]
**Describe the bug**
Tukui -- Failed to find addon version number for game version:

**If you run `pipenv update` on the command line and try again, does the issue go away?**
No

**Log output**
    2020-12-04 03:30:07,394 [DEBUG] [19068] [urllib3.connectionpool] https://www.tukui.org:443 "GET /addons.php?id=186 HTTP/1.1" 200 7291
    2020-12-04 03:30:07,396 [ERROR] [19068] [updater.manager.addon_manager] Failed to find addon version number for game version: GameVersion.agnostic, https://www.tukui.org/addons.php?id=186
    Traceback (most recent call last):
      File "D:\Games\WoWAddonUpdater\updater\site\tukui.py", line 55, in get_latest_version
        version = re.search(f'>{self._version_pattern}<', text).group(1)
    AttributeError: 'NoneType' object has no attribute 'group'

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "D:\Games\WoWAddonUpdater\updater\manager\addon_manager.py", line 100, in update_addon
        latest_version = site.get_latest_version()
      File "D:\Games\WoWAddonUpdater\updater\site\tukui.py", line 59, in get_latest_version
        raise self.version_error() from e
    updater.site.abstract_site.SiteError: Failed to find addon version number for game version: GameVersion.agnostic, https://www.tukui.org/addons.php?id=186

**Comment by grrttedwards** [comment]
I can reproduce this, but it's interesting that it doesn't happen on the URL that the test suite uses. I'll look into it.

**Comment by grrttedwards** [comment]
@RavenDT I've fixed this on develop and can get it released soon. In the meantime, you can use the develop branch (if you're familiar with doing that) for the fix!

Thanks!

**Comment by grrttedwards** [comment]
Released 1.8.1, thanks
