### ISSUE TITLE
Error with wowinterface, BugSack only

### ISSUE THREAD

**Issue by ilu33** [grrttedwards/wow-addon-updater#197]
**Describe the bug**
Log throws an error on BugSack, but afaik it does update anyway.

**If you run `pipenv update` on the command line and try again, does the issue go away?**
No

**Log output**
2022-09-01 19:26:20,169 [INFO ] [140065474021120] [updater.manager.addon_manager] Installing/updating addon: BugSack to version: v9.2.5...

2022-09-01 19:26:20,179 [ERROR] [140065351116544] [updater.manager.addon_manager] 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/wow-addon-updater/updater/manager/addon_manager.py", line 91, in update_addon
    addon_name = site.get_addon_name()
  File "/wow-addon-updater/updater/site/wowinterface.py", line 44, in get_addon_name
    addon_name = re.search(r"info[0-9]+-(?P<name>.+)\.html", addon_name).group('name')
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by grrttedwards** [comment]
Hey, I'm not able to reproduce this. It's possible they uploaded a new package maybe, or there was something wrong with the page at the time?

```
PS C:\wow-addon-updater> pipenv run python -m updater
Installing/updating addon: BugSack to version: v10.0.0...

Name           Prev. Version  New Version
────           ─────────────  ───────────
BugSack        -----          v10.0.0
PS C:\wow-addon-updater> 
```
