### ISSUE TITLE
codecs.charmap_encode issue

### ISSUE THREAD

**Issue by arsirantala** [grrttedwards/wow-addon-updater#201]
Getting in Windows 11 a following error when running the updater:

```
$ ./run_Windows.bat
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Arsi\AppData\Local\Programs\Python\Python311\Lib\logging\__init__.py", line 1113, in emit
    stream.write(msg + self.terminator)
  File "C:\Users\Arsi\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 51-54: character maps to <undefined>
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Arsi\Documents\wow-addon-updater\updater\__main__.py", line 87, in <module>
    main()
  File "C:\Users\Arsi\Documents\wow-addon-updater\updater\__main__.py", line 78, in main
    AddonManager(args.config).update_all()
  File "C:\Users\Arsi\Documents\wow-addon-updater\updater\manager\addon_manager.py", line 78, in update_all
    self.display_results()
  File "C:\Users\Arsi\Documents\wow-addon-updater\updater\manager\addon_manager.py", line 197, in display_results
    logger.info('\n\n' + '\n'.join(results))
  File "C:\Users\Arsi\AppData\Local\Programs\Python\Python311\Lib\logging\__init__.py", line 1489, in info
    self._log(INFO, msg, args, **kwargs)
  File "C:\Users\Arsi\AppData\Local\Programs\Python\Python311\Lib\logging\__init__.py", line 1634, in _log
    self.handle(record)
  File "C:\Users\Arsi\AppData\Local\Programs\Python\Python311\Lib\logging\__init__.py", line 1644, in handle
    self.callHandlers(record)
  File "C:\Users\Arsi\AppData\Local\Programs\Python\Python311\Lib\logging\__init__.py", line 1706, in callHandlers
    hdlr.handle(record)
  File "C:\Users\Arsi\Documents\wow-addon-updater\updater\__main__.py", line 18, in handle
    super().handle(record)
Message: '\n\nName           Prev. Version  New Version    \n\u2500\u2500\u2500\u2500           \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500  \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500    '
Arguments: ()
```

pip freeze output:

```
$ pip freeze
beautifulsoup4==4.9.3
certifi==2021.5.30
chardet==4.0.0
cloudscraper==1.2.58
distlib==0.3.6
filelock==3.8.0
idna==2.10
pipenv==2022.11.11
platformdirs==2.5.4
pyparsing==2.4.7
requests==2.25.1
requests-toolbelt==0.9.1
soupsieve==2.2.1
urllib3==1.26.5
virtualenv==20.16.7
virtualenv-clone==0.5.7
```

Python version:

```
$ python --version
Python 3.11.0
```

**Comment by grrttedwards** [comment]
Hello. This looks similar to this issue https://github.com/grrttedwards/wow-addon-updater/issues/98

Please try another shell, it is maybe a problem with your localization in the shell you're using?

**Comment by arsirantala** [comment]
Thanks, will try that one

**Comment by arsirantala** [comment]
I was able to get this issue sorted, by checking me environment. Hence this is not a issue anymore. Closing this issue.
