### ISSUE TITLE
WowInterface Classic addon won't download

### ISSUE THREAD

**Issue by mishugashu** [grrttedwards/wow-addon-updater#66]
Download Page:

https://www.wowinterface.com/downloads/download24980-QuestLogEx

Returns with:
```
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mishugashu/git/wow-addon-updater/updater/manager/addon_manager.py", line 75, in update_addon
    addon_name = site.get_addon_name()
  File "/home/mishugashu/git/wow-addon-updater/updater/site/wowinterface.py", line 44, in get_addon_name
    addon_name = re.search(r"info[0-9]+-(?P<name>[a-zA-z0-9]+)\.html", addon_name).group('name')
AttributeError: 'NoneType' object has no attribute 'group'

```

Info Page:

https://wowinterface.com/downloads/info24980-QuestLogEx.html

Returns with:

```Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mishugashu/git/wow-addon-updater/updater/manager/addon_manager.py", line 73, in update_addon
    site = site_handler.get_handler(addon_url, self.game_version)
  File "/home/mishugashu/git/wow-addon-updater/updater/site/site_handler.py", line 31, in get_handler
    raise UnknownSiteError(f"Unknown addon source: {url}")
updater.site.site_handler.UnknownSiteError: Unknown addon source: https://wowinterface.com/downloads/info24980-QuestLogEx.html
```

Python version: 3.7.4.

**Comment by mishugashu** [comment]
Got it to work. Needs the "info" url, but with a "www." in front. Maybe make it less strict about the "www"?
