### ISSUE TITLE
UnicodeEncodeError 'charmap' can't encode - Python 3.8

### ISSUE THREAD

**Issue by Swatto86** [grrttedwards/wow-addon-updater#98]
Hello All,

Happy New Year

I am using Python 3.8 and getting the following error on Windows:

Any idea how to fix this please?

.\run_Windows.bat : Traceback (most recent call last):
At line:1 char:1
+ .\run_Windows.bat
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Traceback (most recent call last)::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
  File "c:\python38\Lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\Lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\users\SteveWatson\wow-addon-updater\updater\__main__.py", line 46, in <module>
    main()
  File "C:\users\SteveWatson\wow-addon-updater\updater\__main__.py", line 39, in main
    AddonManager(args.config).update_all()
  File "C:\users\SteveWatson\wow-addon-updater\updater\manager\addon_manager.py", line 77, in update_all
    self.display_results()
  File "C:\users\SteveWatson\wow-addon-updater\updater\manager\addon_manager.py", line 188, in display_results
    print("".join(word.ljust(col_width) for word in row))
  File "C:\Users\SteveWatson\.virtualenvs\wow-addon-updater--huNV0kt\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-3: character maps to <undefined>

**Comment by grrttedwards** [comment]
Hi @Swatto86 , wow you’ve found a weird one! My guess is that your console doesn’t know what to do with some Unicode characters when asked to print them. Do you happen to have a different default font chosen for your cmd?

**Comment by Swatto86** [comment]
> Hi @Swatto86 , wow you’ve found a weird one! My guess is that your console doesn’t know what to do with some Unicode characters when asked to print them. Do you happen to have a different default font chosen for your cmd.. or is that powershell?

Hi @grrttedwards - you are right, I was using a custom font called 'Hack' and also running in the Powershell ISE. I ran in command prompt and it is fine.  Thanks so much for the tip - great work with the script, I am currently trying to learn Python myself and I am using your script as inspiration.
